export const technologies = {
  comfort: [
    "JavaScript / TypeScript",
    "ReactJS",
    "NextJS",
    "Redux",
    "Jest / Enzyme",
    "HTML5 / CSS3",
    "Git",
    "Webpack",
    "Photoshop / Figma / Zeplin",
    "Tailwind / Material / Bootstrap",
    "Responsive Layout and Design",
    "Mobile First Thinking",
  ],
  experience: [
    "NodeJS (ExpressJS/NestJS)",
    "MongoDB",
    "PostgreSQL",
    "Firebase",
    "AWS",
    "GraphQL",
    "Cypress",
    "Java",
    "Python",
  ],
};
